# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Evy < Formula
  desc "Evy is a simple programming language."
  homepage "https://evy.dev"
  version "0.1.152"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/evylang/evy/releases/download/v0.1.152/evy_0.1.152_darwin_amd64.tar.gz"
      sha256 "396794ab84fc81ef6a4dc28698bdea7711fc2a30ed10b803c538e40963dc54f4"

      def install
        bin.install "evy"
      end
    end
    on_arm do
      url "https://github.com/evylang/evy/releases/download/v0.1.152/evy_0.1.152_darwin_arm64.tar.gz"
      sha256 "5977ddb1cdd3729e17a9305253624ed273d11e22966742880309066b2d6ae33b"

      def install
        bin.install "evy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evylang/evy/releases/download/v0.1.152/evy_0.1.152_linux_amd64.tar.gz"
        sha256 "9c2e4e62622275cceeac3982166263ab8a562f67e04bda13cbf079a6cbf92b7b"

        def install
          bin.install "evy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evylang/evy/releases/download/v0.1.152/evy_0.1.152_linux_arm64.tar.gz"
        sha256 "e8cf2e23019215ea5c55265589a3bf4a9f304f21524c356cc790480cae5acbbc"

        def install
          bin.install "evy"
        end
      end
    end
  end
end
