# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Evy < Formula
  desc "Evy is a simple programming language."
  homepage "https://evy.dev"
  version "0.1.105"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/evylang/evy/releases/download/v0.1.105/evy_0.1.105_darwin_amd64.tar.gz"
      sha256 "b247b243d30161f4e02aabda067ffca9bdb86e89df5d6d159e346d033ffc92a8"

      def install
        bin.install "evy"
      end
    end
    on_arm do
      url "https://github.com/evylang/evy/releases/download/v0.1.105/evy_0.1.105_darwin_arm64.tar.gz"
      sha256 "8b9db32175421579cbdf484bfe31b1ae177fcdcad0c104d26ccf973f314edd99"

      def install
        bin.install "evy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evylang/evy/releases/download/v0.1.105/evy_0.1.105_linux_amd64.tar.gz"
        sha256 "fae46ae8f32e30d6122e5c810077f4fcdac8eb3de610e2bb9b279fd217583a9c"

        def install
          bin.install "evy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evylang/evy/releases/download/v0.1.105/evy_0.1.105_linux_arm64.tar.gz"
        sha256 "95e9067eee4041052ebd070ae617b57c14b0bca053344e3b902da59872f660a7"

        def install
          bin.install "evy"
        end
      end
    end
  end
end
