# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pratt < Formula
  desc "Pratt is a minimal Pratt parser."
  homepage "https://evy.dev"
  version "0.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evylang/pratt/releases/download/v0.0.4/pratt_0.0.4_darwin_amd64.tar.gz"
      sha256 "6f7db23eef6f3a53c34edcf4c75cecfa414ace6176c4ae8a1215ba88e702b10b"

      def install
        bin.install "pratt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evylang/pratt/releases/download/v0.0.4/pratt_0.0.4_darwin_arm64.tar.gz"
      sha256 "74ce09c0a0c5b8efefa8f5590a5a66a8af81481f78f868f8a7684bff124cc349"

      def install
        bin.install "pratt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/evylang/pratt/releases/download/v0.0.4/pratt_0.0.4_linux_amd64.tar.gz"
      sha256 "d53b99072bd8aedf839c27a8deb4dd45f35de01f158fc69a9c22cc11c1108c08"

      def install
        bin.install "pratt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evylang/pratt/releases/download/v0.0.4/pratt_0.0.4_linux_arm64.tar.gz"
      sha256 "6c4e2315b13e570f19525e0549bfdcbfb764db3cc3e614708f612f1e14571862"

      def install
        bin.install "pratt"
      end
    end
  end
end
